import { Component } from '@angular/core';

@Component({
  selector: 'app-test5',
  imports: [],
  templateUrl: './test5.component.html',
  styleUrls: [
    './test5.component.css',
    './test5.component.1.css',
    './test5.component.2.css',
    './test5.component.3.css',
    './test5.component.4.css',
    './test5.component.5.css',
    './test5.component.6.css',
    './test5.component.7.css',
    './test5.component.8.css',
    './test5.component.9.css',
    './test5.component.10.css',
    './test5.component.11.css',
    './test5.component.12.css',
    './test5.component.13.css',
    './test5.component.14.css',
    './test5.component.15.css',
    './test5.component.16.css',
    './test5.component.17.css',
    './test5.component.18.css',
    './test5.component.19.css',
    './test5.component.20.css',
    './test5.component.21.css',
    './test5.component.22.css',
    './test5.component.23.css',
    './test5.component.24.css',
    './test5.component.25.css',
    './test5.component.26.css',
    './test5.component.27.css',
    './test5.component.28.css',
    './test5.component.29.css',
    './test5.component.30.css',
    './test5.component.31.css',
    './test5.component.32.css',
    './test5.component.33.css',
    './test5.component.34.css',
    './test5.component.35.css',
    './test5.component.36.css',
    './test5.component.37.css',
    './test5.component.38.css',
    './test5.component.39.css',
    './test5.component.40.css',
    './test5.component.41.css',
    './test5.component.42.css',
  ],
})
export class Test5Component {}
